---
- name: down | Block
  vars:
    __compose_install_dir: "{{ lookup('vars', __compose_artificer_parent_role_prefix + '_compose_install_dir') }}"
    __compose_project_root_dir: "{{ lookup('vars', __compose_artificer_parent_role_prefix + '_compose_project_root_dir') }}"
    __compose_files: "{{ lookup('vars', __compose_artificer_parent_role_prefix + '_compose_files', default=omit) }}"
    __compose_profiles: "{{ lookup('vars', __compose_artificer_parent_role_prefix + '_compose_profiles', default=omit) }}"
    __down_remove_orphans: "{{ lookup('vars', __compose_artificer_parent_role_prefix + '_down_remove_orphans', default=true) }}"
    __down_remove_images: "{{ lookup('vars', __compose_artificer_parent_role_prefix + '_down_remove_images', default=omit) }}"
    __down_remove_volumes: "{{ lookup('vars', __compose_artificer_parent_role_prefix + '_down_remove_volumes', default=false) }}"
    # number of latest snapshots to keep when pruning, consumed by down_zfs.yml/down_btrfs.yml
    __compose_artificer_snapshots_keep: "{{ lookup('vars', __compose_artificer_parent_role_prefix + '_down_snapshots_keep', default=1) | int }}"
  block:
    - name: down | Shut down and remove services for {{ __compose_artificer_compose_project_name }}
      become: true
      community.docker.docker_compose_v2:
        project_src: "{{ __compose_install_dir.dir }}"
        state: "absent"
        remove_orphans: "{{ __down_remove_orphans }}"
        remove_images: "{{ __down_remove_images | default(omit) }}"
        remove_volumes: "{{ __down_remove_volumes }}"
        files: "{{ __compose_files | default(omit) }}"
        profiles: "{{ __compose_profiles | default(omit) }}"
      register: __compose_artificer_compose_down

    - name: down | Prune zfs snapshots for {{ __compose_artificer_compose_project_name }}
      become: true
      ansible.builtin.import_tasks: down_zfs.yml
      when:
        - ansible_facts['zfs_datasets'] is defined

    - name: down | Prune btrfs snapshots for {{ __compose_artificer_compose_project_name }}
      become: true
      ansible.builtin.import_tasks: down_btrfs.yml
      when:
        - __compose_artificer_btrfs_info is defined
  rescue:
    - name: down | Failure during shutdown for {{ __compose_artificer_compose_project_name }}
      ansible.builtin.fail:
        msg: "{{ ansible_failed_task }}"
