---
- name: install | Block
  vars:
    __compose_install_dir: "{{ lookup('vars', __compose_artificer_parent_role_prefix + '_compose_install_dir') }}"
    __compose_project_root_dir: "{{ lookup('vars', __compose_artificer_parent_role_prefix + '_compose_project_root_dir') }}"
    __compose_files: "{{ lookup('vars', __compose_artificer_parent_role_prefix + '_compose_files') | default(omit) }}"
    __maintenance: "{{ lookup('vars', __compose_artificer_parent_role_prefix + '_maintenance', default=false) }}"
    __compose_project_dirs: "{{ lookup('vars', __compose_artificer_parent_role_prefix + '_compose_project_dirs') }}"
    __compose_content: "{{ lookup('vars', __compose_artificer_parent_role_prefix + '_compose_content') }}"
  block:
    - name: install | Execute zfs tasks for {{ __compose_artificer_compose_project_name }}
      become: true
      ansible.builtin.import_tasks: install_zfs.yml
      when:
        - ansible_zfs_datasets is defined

    - name: install | Execute btrfs tasks for {{ __compose_artificer_compose_project_name }}
      become: true
      ansible.builtin.import_tasks: install_btrfs.yml
      when:
        - __compose_artificer_btrfs_info is defined

    - name: install | Create directories for {{ __compose_artificer_compose_project_name }}
      become: true
      ansible.builtin.file:
        path: "{{ __folder.value.dir | mandatory }}"
        state: directory
        owner: "{{ __folder.value.owner | default(compose_artificer_default_dir_owner) }}"
        group: "{{ __folder.value.group | default(compose_artificer_default_dir_group) }}"
        mode: "{{ __folder.value.mode | default(compose_artificer_default_dir_mode) }}"
        recurse: "{{ __folder.value.recurse | default(compose_artificer_default_dir_recurse) }}"
        attributes: "{{ __folder.value.attributes | default(omit) }}"
      register: __compose_artificer_project_dir_creation
      loop: "{{ __compose_project_dirs | dict2items }}"
      loop_control:
        label: "{{ __folder.value.dir | mandatory }}"
        loop_var: __folder

    - name: install | Upload docker-compose files for {{ __compose_artificer_compose_project_name }}
      become: true
      ansible.builtin.template:
        src: docker-compose.yml.j2
        dest: "{{ __compose_install_dir.dir }}/docker-compose.yml"
        owner: root
        group: root
        mode: "0600"
        backup: true
      register: __compose_artificer_compose_file

    - name: install | Install UnRAID files for {{ __compose_artificer_compose_project_name }}
      become: true
      ansible.builtin.import_tasks: install_unraid.yml
      when: ansible_distribution == 'Unraid'
  rescue:
    - name: install | An error occurred on installation for {{ __compose_artificer_compose_project_name }}
      ansible.builtin.debug:
        msg: An error occurred when installing {{ __compose_artificer_compose_project_name }} - Task {{ ansible_failed_task.name }} failed

    - name: install | Check if compose file backup was created
      become: true
      ansible.builtin.stat:
        path: "{{ __compose_artificer_compose_file.backup_file | default('/dummy/path') }}"
      register: __compose_artificer_compose_file_backup
      when: __compose_artificer_compose_file.failed is defined and __compose_artificer_compose_file.failed

    - name: install | Restore compose file backup for {{ __compose_artificer_compose_project_name }}
      become: true
      ansible.builtin.copy:
        src: "{{ __compose_artificer_compose_file.backup_file }}"
        dest: "{{ __compose_install_dir.dir }}/docker-compose.yml"
        owner: root
        group: root
        mode: "0600"
        remote_src: true
      when: __compose_artificer_compose_file.failed is defined and __compose_artificer_compose_file.failed and __compose_artificer_compose_file_backup.stat.exists

    - name: install | Remove compose file backup for {{ __compose_artificer_compose_project_name }}
      become: true
      ansible.builtin.file:
        path: "{{ __compose_artificer_compose_file.backup_file }}"
        state: absent
      when: __compose_artificer_compose_file.failed is defined and __compose_artificer_compose_file.failed and __compose_artificer_compose_file_backup.stat.exists

    - name: install | Installation failed for {{ __compose_artificer_compose_project_name }}
      ansible.builtin.fail:
        msg: "{{ ansible_failed_task }}"
