---
# handlers file for shawly.compose_artificer

- name: Restart services
  become: true
  ansible.builtin.command:
    cmd: docker compose --progress=plain restart
    chdir: "{{ install_dir.dir }}"
  when: not _docker_compose.changed
