---
# handlers file for shawly.compose_artificer

- name: Restart services
  become: true
  ansible.builtin.command:
    cmd: docker compose --progress=plain restart
    chdir: "{{ __compose_install_dir.dir }}"
  register: _docker_compose_restart
  changed_when: ("Started" in (_docker_compose_restart.stderr_lines | trim))
  vars:
    __compose_install_dir: "{{ lookup('vars', compose_artificer_role_prefix + '_compose_install_dir') }}"
    __maintenance: "{{ lookup('vars', compose_artificer_role_prefix + '_maintenance') }}"
  when: not (compose_artificer_compose_file.changed or _docker_compose_up.changed) and not ansible_check_mode and not __maintenance
