---
# handlers file for shawly.compose_artificer

- name: Restart services
  become: true
  community.docker.docker_compose_v2:
    project_src: "{{ __compose_install_dir.dir }}"
    state: "restarted"
    files: "{{ __compose_files | default(omit) }}"
  vars:
    __compose_install_dir: "{{ lookup('vars', __compose_artificer_parent_role_prefix + '_compose_install_dir') }}"
    __maintenance: "{{ lookup('vars', __compose_artificer_parent_role_prefix + '_maintenance') }}"
    __compose_files: "{{ lookup('vars', __compose_artificer_parent_role_prefix + '_compose_files', default=omit) }}"
    __force_restart: "{{ lookup('vars', __compose_artificer_parent_role_prefix + '_force_restart', default=false) }}"
  when: __force_restart or (not (__compose_artificer_compose_file.changed or __compose_artificer_compose_up.changed) and not __maintenance)
