---
# handlers file for shawly.compose_artificer

- name: Restart services
  become: true
  ansible.builtin.command:
    cmd: docker compose --progress=plain restart
    chdir: "{{ lookup('vars', compose_artificer_role_prefix + '_compose_install_dir').dir }}"
  changed_when: true
  when: not _docker_compose.changed
